import React from "react";
import { render } from "@testing-library/react";
import ErrorBoundary from "../ErrorBoundary";
import ConstructorContext from "../../../../engine/ConstructorContext";
import mockAppData from "../../../../mockData/mockAppData";

const ComponentWithError = () => {
  throw new Error("Custom error");
};

const contextValue = [
  {
    response: mockAppData,
    scores: {
      absence: 0,
      "trigger-points-sick-pay": 5,
    },
  },
  jest.fn(),
];

describe("ErrorBoundary", () => {
  const Wrapper = () => (
    <ConstructorContext.Provider value={contextValue}>
      <ErrorBoundary>
        <ComponentWithError />
      </ErrorBoundary>
    </ConstructorContext.Provider>
  );

  it("should display error message on error generated by child", () => {
    const { getByText } = render(<Wrapper />);

    getByText("errorPage");
  });
});
